config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  get "up" => "rails/health#show", as: :rails_health_check

  # Authentication
  devise_for :users, controllers: {
    sessions: "users/sessions"
  }

  get "unauthorized", to: "pages#unauthorized"
  get "accueil", to: "pages#home", as: :home
  get "recherche", to: "pages#search", as: :search
  get "statistiques", to: "statistics#index"

  # Routes pour les graphiques de test
  resources :charts, only: [:index] do
    collection do
      get :line_data
      get :bar_data
    end
  end

  namespace :admin do
    resources :users do
      member do
        get :impersonate
      end
    end

    root to: "users#index"
  end

  resources :users do
    collection do
      post :stop_impersonating
      post :set_time_zone
    end
  end

  devise_scope :user do
    post "authenticate", to: "users/sessions#create"
  end

  resources :establishments, only: [:show], path: "etablissements", param: :siret do
    member do
      get :insee_widget
      get :data_urssaf_widget
      get :data_effectif_ap_widget
    end
    resources :establishment_trackings, only: %i[new create show destroy edit update], path: "accompagnements" do
      member do
        get :confirm
        patch :complete
        get :manage_contributors
        patch :update_contributors
        delete :remove_referent
        delete :remove_participant
      end
      resources :summaries, only: %i[create edit update] do
        get :cancel, on: :member
      end
      resources :comments, only: %i[create edit update destroy]
      resources :contacts, only: %i[new create edit update destroy] do
        member do
          get :archive
        end
      end
    end
  end

  resources :companies, path: "entreprises", only: %i[show], param: :siren do
    member do
      get :insee_widget
      get :data_urssaf_widget
      get :data_effectif_ap_widget
      get :financial_widget
      get :establishments_widget
      get :establishment_trackings_list_widget
    end
  end

  resources :establishment_trackings, only: [:index], defaults: { format: :html }, path: "accompagnements"

  # Build a new 'accompagnement' from the Vue JS legacy app (using siret as query param)
  get "establishment_trackings/new_by_siret", to: "establishment_trackings#new_by_siret",
                                              as: "new_establishment_tracking_by_siret"

  root "establishment_trackings#index"
end

app/models/comment.rb
class Comment < ApplicationRecord
  has_paper_trail

  belongs_to :establishment_tracking, optional: false
  belongs_to :network, optional: false
  belongs_to :user, optional: false

  after_create :update_establishment_tracking_modified_at
  after_create :create_establishment_tracking_version
  after_update :create_establishment_tracking_version
  after_destroy :create_establishment_tracking_version

  validates :content, presence: true
  validates :network_id, presence: true

  private

  def update_establishment_tracking_modified_at
    return if establishment_tracking.instance_variable_get(:@skip_modified_at_update)

    establishment_tracking.update!(modified_at: Date.current)
  end

  def create_establishment_tracking_version
    return if establishment_tracking.instance_variable_get(:@skip_modified_at_update)

    event_type = if destroyed?
                   "deleted"
                 elsif previous_changes.key?("id")
                   "created"
                 else
                   "modified"
                 end

    establishment_tracking.paper_trail_event = "comment_#{event_type}"
    establishment_tracking.paper_trail.save_with_version
  end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
  before_action :set_establishment_and_tracking
  before_action :set_comment, only: %i[edit update destroy]
  before_action :authorize_comment, only: %i[edit update destroy]

  before_action :set_paper_trail_whodunnit

  def edit; end

  def create
    @comment = build_comment
    if @comment.save
      flash.now[:notice] = t(".success")
    else
      render turbo_stream: turbo_stream.update("new_comment_#{@comment.network.name.parameterize}",
                                               partial: "comments/form",
                                               locals: { comment: @comment, network: @comment.network },
                                               status: :unprocessable_entity)
    end
  end

  def update
    if @comment.update(comment_params)
      flash.now[:notice] = t(".success")
    else
      render turbo_stream: turbo_stream.update("comment_#{@comment.id}",
                                               partial: "comments/form",
                                               locals: { comment: @comment, network: @comment.network },
                                               status: :unprocessable_entity) end
  end

  def destroy
    @comment.destroy
    flash.now[:notice] = t(".success")
  end

  private

  def set_establishment_and_tracking
    @establishment = Establishment.find_by!(siret: params[:establishment_siret])
    @establishment_tracking = @establishment.establishment_trackings.find(params[:establishment_tracking_id])
  end

  def set_comment
    @comment = @establishment_tracking.comments.find(params[:id])
  end

  def authorize_comment
    authorize @comment
  end

  def comment_params
    params.require(:comment).permit(:content, :network_id)
  end

  def build_comment
    comment = @establishment_tracking.comments.new(comment_params)
    comment.user = current_user
    comment.network ||= current_user.networks.where.not(name: "codefi").first
    comment
  end
end

app/views/comments/_comment.html.erb
<%= turbo_frame_tag dom_id(comment) do %>

  <div class="comment-container fr-mb-3w" data-controller="auto-resize">
    <div class="comment-header">
      <div class="avatar">
        <span><%= comment.user.full_name[0..1].upcase %></span>
      </div>
      <div class="author-details">
        <strong><%= comment.user.display_name %></strong>
      </div>
    </div>

    <div class="comment-content">
      <p>
        <%= markdown(comment.content) %>
      </p>
    </div>

    <div class="comment-footer">
      <span>le <%= l(comment.created_at, format: :custom) %> (il y a <%= time_ago_in_words(comment.created_at) %>)</span>
      <% if comment.user == current_user && policy(@establishment_tracking).edit? %>
        <%= link_to "Modifier", edit_establishment_establishment_tracking_comment_path(@establishment, @establishment_tracking, comment), data: { turbo_frame: dom_id(comment), turbo_stream: true, action: "auto-resize#focus" }, class: "edit-link", title: "Modifier ce commentaire" %>
        <%= link_to "Supprimer", establishment_establishment_tracking_comment_path(@establishment, @establishment_tracking, comment), method: :delete, data: { turbo_confirm: "Êtes-vous sûr ?", turbo_method: :delete, turbo_stream: true }, class: "delete-link", title: "Supprimer ce commentaire" %>
      <% end %>
    </div>
  </div>
<% end %>

app/views/comments/_form.html.erb
<% if policy(@establishment_tracking).edit? %>
  <%= form_with(model: [ @establishment, @establishment_tracking, comment ], local: false, class: 'fr-mb-3w') do |form| %>
    <%= form.hidden_field :network_id, value: network.id %>
    <div class="fr-input-group <%= 'fr-input-group--error' if comment.errors[:content].any? %>">
      <%= form.text_area :content,
                         class: "fr-input",
                         placeholder: "Taper votre nouveau commentaire",
                         data: { controller: "auto-resize", action: "input->auto-resize#resize" } %>      <% comment.errors.each do |error| %>
        <% if error.attribute == :content || error.attribute == :network %>
          <p id=<%= "comment_#{error.attribute}_error_#{network.name.parameterize}" %> class="fr-error-text">
            <%= error.full_message %>
          </p>
        <% end %>
      <% end %>
    </div>
    <%= form.submit "Envoyer", class: "fr-btn" %>
  <% end %>
<% end %>

app/views/comments/create.turbo_stream.erb
<%= turbo_stream.prepend "comments_#{@comment.network.name.parameterize}" do %>
  <%= render partial: "comments/comment", locals: { comment: @comment, network: @comment.network } %>
<% end %>

<%= turbo_stream.update "new_comment_#{@comment.network.name.parameterize}" do %>
  <%= render "comments/form", comment: Comment.new, network: @comment.network %>
<% end %>

<%= turbo_stream.replace "flash" do %>
  <div id="flash" class="fr-alert fr-alert--success" aria-live="polite">
    <%= notice %>
  </div>
<% end %>

<%= turbo_stream.remove "no_comments_message_#{@comment.network.name.parameterize}" %>

app/views/comments/destroy.turbo_stream.erb
<%= turbo_stream.remove dom_id(@comment) %>

<%= turbo_stream.replace "flash" do %>
  <div id="flash" class="fr-alert fr-alert--success" aria-live="polite">
    <%= notice %>
  </div>
<% end %>

app/views/comments/edit.turbo_stream.erb
<%= turbo_stream.update dom_id(@comment) do %>
  <%= render partial: "comments/form", locals: { comment: @comment, network: @comment.network } %>
<% end %>

app/views/comments/update.turbo_stream.erb
<%= turbo_stream.update dom_id(@comment) do %>
  <%= render partial: "comments/comment", locals: { comment: @comment } %>
<% end %>

<%= turbo_stream.replace "flash" do %>
  <div id="flash" class="fr-alert fr-alert--success" aria-live="polite">
    <%= notice %>
  </div>
<% end %>